/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.derf.HelloRedis;

/*
Notes for using with Learn:

- Just specify path to bb-config.properties as cmd line arg
- Timestamp logging to stdout
 */

import redis.clients.jedis.Jedis;
import redis.clients.jedis.ScanParams;
import redis.clients.jedis.ScanResult;

import java.util.Arrays;

public class App {
  private static final String PREFIX = "2066518051";

  private static void stream(String sourceServer, int sourcePort, String destServer, int destPort) {
    Jedis source = new Jedis(sourceServer, sourcePort);
    Jedis dest = new Jedis(destServer, destPort);

    String nextCursor = "0";
    ScanParams scanParams = new ScanParams();
    scanParams.match(PREFIX + "*");

    System.out.println("Checking...");
    while (true) {
      ScanResult<String> scanResult = source.scan(nextCursor, scanParams);

      for (String key: scanResult.getResult()) {
        byte[] sourceDumpedValue = source.get(key.getBytes());
        byte[] destDumpedValue = dest.get(key.getBytes());
        if (Arrays.equals(sourceDumpedValue, destDumpedValue)) {
          System.out.println(String.format("%s: values match: OK", key));
        } else {
          throw new RuntimeException("Values do not match for " + key);
        }
      }

      if (scanResult.isCompleteIteration()) {
        break;
      }

      nextCursor = scanResult.getCursor();
    }
  }

  private static String getServerFromArg(String arg) {
    return arg.split(":")[0];
  }

  private static int getPortFromArgs(String arg) {
    return arg.split(":").length == 2 ? Integer.parseInt(arg.split(":")[1]) : 6379;
  }

  public static void main(String[] args) {
    if (args.length != 2) {
      System.err.println("Usage: HelloRedis server1:port server2:port");
      System.exit(1);
    }

    String sourceServer = getServerFromArg(args[0]);
    int sourcePort = getPortFromArgs(args[0]);
    String destServer = getServerFromArg(args[1]);
    int destPort = getPortFromArgs(args[1]);

    stream(sourceServer, sourcePort, destServer, destPort);
  }
}
